### ISSUE TITLE
My PC was Random restart after installed TabNine on VSCode ?

### ISSUE THREAD

**Issue by silkyland** [codota/TabNine#158]
I was installed TabNine on VSCode my computer got a random restart, anyone else got the same problem as me?

SPEC: 
AMD Ryzen 7 3700x
Ram 32 GB 8x4 Bus 2600
Board: Aurus Ultra X570 
SSD: m2 NVME 1TB Crucial

**Comment by zxqfl** [comment]
Could you please provide steps to reproduce the issue?

**Comment by silkyland** [comment]
When I press ctrl + spacebar for use suggestion it random crashed.

**Comment by amircodota** [comment]
If this still reproduces, please answer the following:

1. Which os and version are you using?
2. Do you have TabNine local enabled? Does it reproduce if disabled?
3. Does your pc report a reason for the crash?

**Comment by cakasuma** [comment]
i got the similar issue here, but its VSCode restart, not PC restart. i checked all ram and cpu are fine. also using AMD Ryzen, but Ryzen 5 1600

1. windows 10 Pro 2004
2. yes, tabnine local enabled, and if its disabled it's normal
3. no, just a VSCode restart, not PC restart for me

**Comment by Soulyyyy** [comment]
I got the same thing with AMD Ryzen 7 2700X and 30 gb RAM. Checked all stats and seems all fine, no CPU or RAM overload. However, my computer restarts completely.

1. Windows 11 Pro
2. Does it only when it's enabled
3. Yes, this is a PC restart (Event 41, Kernel Power)

**Comment by maxloo2** [comment]
vscode + tabnine (enabled beta version), win10, 5900x, consistently crashing my whole system (kernel power: 41) after doing ctrl+space a few times. thought it was my unstable CPU at first but after tweaking my clock speed and voltages I found that I literally will not crash doing anything else besides using vscode with tabnine.

I have zero problem using tabnine for months on another MacOS machine (intel CPU). I suspect that tabnine is somehow affecting my CPU therefore causing the crash due to fluctuations of the vcore, but this is just pure assumptions since I have disabled tabnine for the time being and dont plan on doing experiments with it in the near future (spent too much time on trying to troubeshoot this already).

**Comment by msavara** [comment]
I have the same issue. That was crash of whole system. Without any bluescreen or something. I had also this issue when i ran ML.NET from C#, and also python numpy library. Same crash.

**Comment by tomKPZ** [comment]
I'm also hitting this issue with a Ryzen 5950x on Windows 11.  To repro, I just have to launch VSCode with Tabnine installed, and there's a ~50% chance my PC will shut down.  The PC won't turn on even if I press or hold the power button.  I have to physically pull the plug and replug to turn the PC on again.  The issue does not repro when Tabnine is not installed.

**Comment by msavara** [comment]
Great access to the support. And you want to ask for money for your product?

**Comment by maxloo2** [comment]
@msavara I have since moved on to using GitHub Copilot and I must say that it has been a much better experience than with TabNine, not saying that tabnine is bad, but Copilot is just smooth, never encountered a problem. YMMV but for my use case I dont think I will ever go back to TabNine unless Copilot shuts down (lol Microsoft).

**Comment by pheotry** [comment]
I have the same problem when I use tabnine in vscode.
It can recur in my idea when I install tabnine for idea.

OS: win11 pro 22621.1702
CPU: i5-9400

**Comment by pheotry** [comment]
> Same problem with PHPStorm, installed and after some seconds pc goes down. Same thing on another PC.

Check up your username of Windows, if it have special symbol, such as., the pc may be restart.
