### ISSUE TITLE
Sharing between multiple instances

### ISSUE THREAD

**Issue by hissssst** [codota/TabNine#175]
Came here from https://github.com/tbodt/deoplete-tabnine/issues/39 with bunch of questions.

1) Does **TabNine** provide any api for sharing process between multiple instances? How do I use it?
2) If it doesn't have this feature, will it be implemented? When?
3) Are there any ways to control memory consumption?

**Comment by amircodota** [comment]
1. No such api exists at the moment.
2. This is something that was discussed, but will probably not be implemented in the near future. The communication between the editor and tabnine is currently done over standard input and output, so changing it requires quite a bit of work.
3. We have since made several fixes around memory. The memory is currently limited to 2.5g. We might consider allowing changing that limit via config in the future, but currently it is hard coded.

Closing for now.
Feel free to reply and I'll re-open.

**Comment by jcassee** [comment]
@amircodota Not a request to reopen, but a +1 with my use-case.

I'd like to install TabNine in vim, Sublime and IntelliJ, and 6GB is a bit hard to stomach. :smile: I use them for different purposes. It's not easy to quickly enable or disable TabNine in the various plugins, and anyway it's handy even when typing up a quick script.

**Comment by thakkarparth007** [comment]
@amircodota, I have the same issue. I use TabNine in VSCode and Jupyter notebooks and I see several TabNine processes. If sharing isn't practical, a configurable memory limit like you mentioned would be very helpful.
