### ISSUE TITLE
CPU cap

### ISSUE THREAD

**Issue by emilk** [codota/TabNine#186]
When TabNine uses 100% of one core it makes the fan on my laptop go crazy, driving me crazy in turn (I am very sensitive to noise).

A GREAT feature would be to be able to add a cap on the CPU usage, e.g. ensuring TabNine never used more than 20% of one core or similar.

**Comment by amircodota** [comment]
We have since released a version that improves TabNine's memory and cpu consumption.
Would really appreciate if you can test it out and see if the issue you reported still persists.

We have not exactly added a cpu cap - we went about it another way, But I'm hoping the end result will be good enough.

**Comment by yech1990** [comment]
Hi @amircodota , I think a cpu cap is important. For using tabnine as a vim plugin in HPC, once tabnine use too much CPU resource, all the process of a user will be killed.
