### ISSUE TITLE
Always ignore certain file types

### ISSUE THREAD

**Issue by vfonic** [codota/TabNine#209]
I noticed in TabNine logs that it tries to read files like `.DS_Store` and any font and image files.

This doesn't make sense. Especially for `.DS_Store` (and for `Thumbs.db` if Windows still uses these)

This should be ignored by default.

I use Sublime Text 3.

Related issues:
https://github.com/zxqfl/TabNine/issues/15
https://github.com/zxqfl/TabNine/issues/38

**Comment by amircodota** [comment]
You can add a `.tabnineignore` file.

See our [FAQ](https://tabnine.com/faq/) for more details

**Comment by vfonic** [comment]
Hey @amircodota! Thanks for the reply! I think TabNine is an amazing tool!

It would be great if the tool would do this by itself, at least for the files like `.DS_Store` and similar. Do you think there would be a case when someone would need to index those files? Thanks!

**Comment by amircodota** [comment]
I agree that it does not make sense to index these files.
TabNine does not index these files because they are binary. It just logs them, which is admittedly confusing.
The current logic, which I think is not a bad one, is that it tries to index anything that's included in the project, or, more specifically, anything that should be committed to version control.
I think most users have these files in .gitignore (or .hgignore or whatever else) and thus do not see this issue.

**Comment by bertyhell** [comment]
@amircodota Is it also possible to disable tabnine autocomplete in certain files?
For instance intellij has the concept of scratches. When i make a plain text scratch file i don't want tabnine to autocomplete when i press enter, since i'm writing regular text.

![image](https://user-images.githubusercontent.com/1710840/109150336-08edb680-7769-11eb-96a2-47730ae97b18.png)

Adding *.txt to `.tabnineignore` does not seem to resolve this. Probably because that is the ignore file for the model, not the ignore file for autocomplete functionality.

**Comment by amircodota** [comment]
@bertyhell We currently support this in vscode.
This is definitely something we will add for other editors as well in the future.

Are you on vscode?

**Comment by bertyhell** [comment]
No, IntelliJ

**Comment by sterlu** [comment]
+1 would love to ignore Plain Text files in Sublime
