### ISSUE TITLE
Lack of transparency 

### ISSUE THREAD

**Issue by sQVe** [codota/TabNine#228]
Hey :wave:,

I'm one of the collaborators of https://github.com/neoclide/coc-tabnine and I really like the concept of TabNine but I do find it somewhat iffy that it is **closed source** but even more that the project **lacks transparency**. The project is all of a sudden owned by **Codota** and there is no mention of it anywhere.

What is going on and how is this going to impact the future of this project?

**Comment by NilsIrl** [comment]
#229

**Comment by drorweiss** [comment]
Hi @sQVe @NilsIrl 
The acquisition of TabNine by Codota has been published in many tech-business related news sites. We'll soon publish blog posts with some additional views and plans for the future.
TabNine is a commercial product, which is currently closed-source, as it has been since day one.
Our team at Codota is working hard to maintain and improve TabNine, and with the increased bandwidth, you'll see faster progress. We're committed to maintaining the project, including a valuable free plan and giving great service to this terrific community.

**Comment by drorweiss** [comment]
@sQVe Thank you for your patience. You can find the note from Jacob Jackson [here](https://tabnine.com/blog/codota), and my note [here](https://blog.codota.com/tabnine-part-of-codota/). As more developers are now working on TabNine, we have been able to address many of the long-standing issues (notably CPU and memory consumption), and working in full force on the next round of improvements.
Thank you for supporting TabNine!
Dror (CEO @Codota)
