### ISSUE TITLE
Extensive RAM usage

### ISSUE THREAD

**Issue by hassanzhd** [codota/TabNine#236]
I've been using tabnine for some time now and its an amazing tool to be very honest but for some time the RAM usage is bothering me quite a bit. Below attached is a screenshot of it using 17.3% of my total RAM. 

![Screenshot from 2020-03-24 18-35-18](https://user-images.githubusercontent.com/52385322/77431292-4e3d9180-6dfe-11ea-85bb-e5ac93e3fdae.png)

**Comment by Krizz** [comment]
Running the command "lsof | grep TabNine | wc -l" shows me 474,468  files opened by TabNine.  It seems like TabNine keeps opening new files until it hits the ulimit. 
Environment: Visual Studio Code Remote Development on Ubuntu 16.04

**Comment by amircodota** [comment]
@hassanzhd Thank you.

What version of Tabnine are you using?

you can type `tabnine::version` to find out

**Comment by Anthony-Michel** [comment]
Getting the same issue on windows. Didn't notice that before, so i think it's relatively new issue (a couple of weeks may be)

See here, 
![image](https://user-images.githubusercontent.com/20057035/78552629-6b308680-783a-11ea-8ea8-74b52b9206b4.png)
I'm on version 2.6.0, in visual studio (WSL connection), on windows 10

**Comment by Shougo** [comment]
The usage seems normal.

**Comment by Anthony-Michel** [comment]
wait, almost 2GB of memory is normal ?
It's more than Chrome with 60 tabs open...

**Comment by amircodota** [comment]
@Anthony-Michel If you have tabnine local enabled, then yes, it is normal.

**Comment by Anthony-Michel** [comment]
Alright then. Did the memory usage increased a lot in last months, because didn't notice that before.
Any improvement coming to reduce it ?

**Comment by amircodota** [comment]
What maybe changed for you is that deep tabnine local is now enabled for you.
You can disable it using "tabnine::config".

We have made a lot of progress in the last few months in terms of memory and cpu consumption, but at the end of the day, if you do choose to use deep tabnine local, it requires a lot of resources, both in terms of cpu and in terms of memory.

You can choose to use TabNine cloud instead of local (for a fee), which offloads this work to our cloud service.
