### ISSUE TITLE
Changing to a new line unfavorably selects the first suggestion

### ISSUE THREAD

**Issue by munichong** [codota/TabNine#267]
Sometimes I just wanna change to a new line by pressing `enter`. However, this unfavorably selects the first suggestion in the autocompletion dropdown list. 

How should I avoid this?

**Comment by drorweiss** [comment]
Many users choose to disable the default behavior of using Enter to accept completions, to avoid accepting a completion when they intended to start a new line. You can do this by going to Settings → Editor: Accept Suggestion On Enter and setting it to off.

**Comment by munichong** [comment]
> Many users choose to disable the default behavior of using Enter to accept completions, to avoid accepting a completion when they intended to start a new line. You can do this by going to Settings → Editor: Accept Suggestion On Enter and setting it to off.

How I can do this in PyCharm?

**Comment by Tschigger** [comment]
I have exactly the same problem and it makes TabNine borderline unusable. Here is what's happening:

IntelliJ does not offer a way to disable the `Enter` key for completing suggestions. It's not a problem when you use the native autocomplete, because they don't offer any suggestions when, for example, typing a comma. IntelliJ only offers suggestions when you are actually typing letters, in which case you are aware of the suggestions popping up.

TabNine on the other hand also offers suggestions when typing symbols like `,`. So when you want to jump to the end of a line, enter a coma and quickly press enter to get to the new line, you end up auto-completing whatever was suggested. It's extremely annoying and I am baffled that so few people are commenting on this issue. TabNine needs to offer a config that does not autocomplete after specific keys if IntelliJ does not offer that functionality (they should, too).

I attached a short GIF of me trying to add a parameter to a function by adding a comma and pressing `Enter` to get to the new line. TabNine blocks it and my `Enter` ends up autocompleting. I have to press `Space`, `Back` and then `Enter`.


![tabnine](https://user-images.githubusercontent.com/15422817/84587641-abf3df80-ae29-11ea-819d-ba13f5e91dff.gif)

**Comment by Cobertos** [comment]
Same issue here on Sublime 3. I had to add `"auto_complete_commit_on_tab": true,` to my `Preferences.sublime-settings` as mentioned [in the Sublime docs](https://www.sublimetext.com/docs/3/auto_complete.html).

I don't know if it's because TabNine integrates deeper with Sublime 3 now but when I migrated from Windows 10 to Linux Mint, it auto added some new properties I was not expecting.

```diff
@@ -1,5 +1,20 @@
 {
-       "auto_complete": false,
+       "auto_complete": true,
+       "auto_complete_triggers":
+       [
+               {
+                       "characters": ".(){}[],'\"=<>/\\+-|&*%=$#@! ",
+                       "selector": "source.python"
+               },
+               {
+                       "characters": ":.(){}[],'\"=<>/\\+-|&*%=$#@! ",
+                       "selector": "source & - source.python - constant.numeric"
+               },
+               {
+                       "characters": " qazwsxedcrfvtgbyhnujmikolpQAZWSXEDCRFVTGBYHNUJMIKOLP",
+                       "selector": "text"
+               }
+       ],
        "auto_match_enabled": false,
        "color_scheme": "Monokai.sublime-color-scheme",
        "draw_white_space": "all",
```

**Comment by boaz-codota** [comment]
We've implemented some fix to this long time ago. We harness the models to predict a line break, and if he thinks a line break is the most likely suggestion, we don't give suggestions at all.

If anyone still suffer from that UX, please open a new ticket.
