### ISSUE TITLE
Issue downloading model and entering configure menu

### ISSUE THREAD

**Issue by cojoda** [codota/TabNine#290]
**please complete the following information:**	
 - OS version: WSL1 (Ubuntu 18.04 LTS) on Windows 10 1909
 - Editor: vscode
 - Editor version: 1.48.2	
 - Programming language: Java, Python
 - TabNine extension version: 3.0.7
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

Log attached

**Issue Details:**
TabNine didn't want to connect to the remote server to download the local model. It just sat at 0%. I tried typing TabNine::configure into a document and got a blank tab. I left my computer on overnight with vscode closed. I tried restarting vscode this afternoon and it looked like it was working and the model was downloaded.. TabNine::config worked as well. And then it wasn't. It started to attempt download of the local model again with the same hang at 0%. Luckily with the configure tab open I was able to view the logs. I was able to wget the model data and copy it into the location listed under the logs: ".local/share/TabNine/models/<model>.tabninemodel". That seemed to take care of the failed download attempt after a restart. However, TabNine still doesn't seem to be fully working and typing TabNine::config still doesn't work. Other commands like TabNine::version and TabNine::sem ect seem to work.

Edit:
TabNine::config pops up with:
TabNine::configCouldn't start config server. Please create an issue at https://github.com/zxqfl/TabNine.

It seems to be working with the same 3.0.7 version on another desktop running Arch Linux. I don't know if this is just an issue with using WSL1 as it was working on WSL2. Unfortunately, because of an issue between WSL2 and AMD virtualization not allowing my laptop to wake up from sleep I had to downgrade to WSL1.

[tabnine.log](https://github.com/codota/TabNine/files/5176486/tabnine.log)

**Comment by yanir-codota** [comment]
Hi @cojoda, 
Thanks for reaching out, and reporting this. 
In order to better investigate this issue, we'll need some additional info.  
1. Can you check whether the TabNine process is still alive when you experience this issue?
2. In the extension settings of TabNine in vscode, there's an option to add a log file path(this will allow persistence of the logs files). can you kindly set it up to your preferred location and provide us with log the files that will be written to that location (before during and after) the time you experience this issue?
 
this may provide additional inputs for the investigation and allow us to assist you better. 
 
Thanks!
