### ISSUE TITLE
I am curious why my CPU is not supported

### ISSUE THREAD

**Issue by chenweiyj** [codota/TabNine#317]
**please complete the following information:**	
 - OS version: macOS Big Sur 11.1 (20C69)	
 - Editor: vscode
 - Editor version:	1.52.1
 - Programming language: go
 - TabNine extension version:  3.2.63-34
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

I cannot find the logs.

**Issue Details:**
My model is MacBook Pro (Retina, 15-inch, Early 2013), with 2.7 GHz quad-core Intel Core i7, with 16GB memory. However, the tabnine shows my CPU is not supported, and tabnine cloud can be used to do the code autocompletion. But even I can use it by tabnine cloud computing, I still want to know why my CPU is not supported to run deep autocompletion locally.

**Comment by Eransho** [comment]
Hi,
Tabnine requires FMA instructions. See [here](https://www.tabnine.com/faq/#FMA) for more details

**Comment by aschmois** [comment]
Does this means that my vm setup cannot run Tabnine anymore? That would be pretty unfortunate since tabnine is extremely nice and useful to use.

https://www.virtualbox.org/ticket/15471

**Comment by Eransho** [comment]
Not exactly. Tabnine requires your CPU to have FMA instructions.
This is not a new requirement but we didn't reflect it clearly to the users until recently.

If your machine doesn't have FMA instructions, you will have the option to join Tabnine Lite from the config page (the hub) which lets you run Tabnine model in our cloud instead of running it locally.
