### ISSUE TITLE
[feature] Reduce distracting flashing - add preference allowing delay

### ISSUE THREAD

**Issue by floer32** [codota/TabNine#334]
## feature request

I want to be able to configure a delay before TabNine completions show.

This is not about any one IDE, I use TabNine in more than one place, and some editors do not allow config of the autocomplete delay.

## why

The "flashing," too-instant autocomplete can be really distracting -- it happens so much and so fast, I accidentally complete with things that are incorrect, without saving time - such as by an accidental keystroke. But then it will "look right" so I might miss it and lose some time. This happens often enough that I keep having to disable TabNine.

I really TabNine overall, and I recommend it to other people often. The most consistent feedback I hear, personanally, is that TabNine spits out too much too fast. As it stands this is the reason I can't continue with TabNine / TabNine pro.

**Comment by boaz-codota** [comment]
Just to be clear, you are saying that Tabnine is faster from the IDE's completions (coming from the LSP), so you wan't us to make it hang a bit before a result is returned?

**Comment by hangtwenty** [comment]
@boaz-codota clsoe, but I actually want no completions popping up for a short delay. Regardless of the cause, I don't see the flashing autocompletions in other editors/IDE[s]. Maybe it's from their builtins being slow, maybe it's from an intentional short delay they add for UX. I know VS Code has an option built in: 

![image](https://user-images.githubusercontent.com/2420688/107267267-8391a480-69fb-11eb-9deb-9bd0ec48f6f1.png)

... but:

* Seemingly that only affects the editor's built-in completions, so changing it leaves TabNine "flashing" just as fast but with no other completions from the editor (until the delay).
* Plenty of editors do not have this setting. (Namely JetBrains IDEs, which is a large market share last time I checked. Also, TabNine helps the experience using JetBrains IDEs, a lot, because TabNine's speed _is_ amazing, and JetBrain's built-in completions are lacking.)

**Comment by hangtwenty** [comment]
FWIW: I have seen others complain about this on the internet, and when I've suggested TabNine to friends/colleagues, this was their consistent complaint (and reason to stop using it). Fast flashing of suggestions, that have a lot of semantic content (sometimes enough that it's like a mini mental-context-switch just to grok some of the surprising suggestions when they happen; and simple typos produce some wild results sometimes, but which I wouldn't see if I could just backspace etc before it pops up).

**Comment by hangtwenty** [comment]
Implementation-wise, it seems clean to allow global config but then TabNine's editor-plugins handle the autocomplete delay, way that make sense for the editor. But if it's just a delay on the LSP response, that'd work too.
