### ISSUE TITLE
Suggestion: Use the model for code formatting

### ISSUE THREAD

**Issue by PerWiklander** [codota/TabNine#337]
TabNine is very good at suggesting the next line of Scala code for me. Wouldn't it be possible to create a code formatter that looks at existing (committed) code and then applies those patterns to format the currently edited file(s)?

**Comment by yonip23** [comment]
Hi @PerWiklander 

This is probably possible, but since almost any language has its default formatter (as well as a customizable one), I don't see the value of adding such feature to Tabnine.

I'm closing this issue, but thanks for reaching out and showing interest in Tabnine!

Best regards

**Comment by yonip23** [comment]
Hi @PerWiklander,

thanks for reaching out and showing interest in Tabnine!

This is probably possible, but since almost any language has its default formatter (as well as a customizable one), I don't see the value of adding such feature to Tabnine.
That being said, I would be glad to hear from you if think otherwise

Best regards

**Comment by PerWiklander** [comment]
That is true. It is probably only me and my arcane coding standards that would need this. Getting alignment right is hard with any current formatter, but I noticed that Tabnine picks up on the pattern perfectly when suggesting how to finish the current line.
