### ISSUE TITLE
musl and domain names resolution

### ISSUE THREAD

**Issue by geovex** [codota/TabNine#343]
**please complete the following information:**	
 - OS version: arch linux
 - Editor: vscode, 
 - Editor version: 1.53.2
 - Programming language: any
 - TabNine extension version: 3.2.7
 - Engine version: 3.3.65-40

**Issue Details:**
Seems like engine uses musl instead of glibc. Is there any significant reason to do that? Musl DNS subsystem is very limited and leads to incorrect resolutions of local hostnames, ignoring `/etc/nsswitch`, problems with exotic options in `resolv.conf` and etc. The usual symptom is inability to download local model (forever download pending...)

**Comment by amircodota** [comment]
@geovex Thanks for reaching out.

The reason we are using musl is that we wanted a [fully static binary](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html) and [rust has issues static linking glibc](https://users.rust-lang.org/t/statically-link-executable-with-glibc/32648).

This is the first ever complaint I've heard of our musl distribution to date :-)

I'm leaving this open for now - if other people care to weigh in on the decision to use musl instead of glibc.

Side note: If the local model fails to download, we provide manual instructions on how to achieve the same thing in the Tabnine hub.

**Comment by geovex** [comment]
You also can refine code to not resolve local hostname or fallback to ::1. The issue with model is that it's not exactly fails, it's stuck in "pending..." state and no other instructions are given(in new interface).

**Comment by amircodota** [comment]
@geovex Can you give some more details about your use case? Why do you need to connect to localhost?
Is it some sort of networking configuration?

**Comment by geovex** [comment]
I can't reproduce it after i fixed it. This is strange. It looked like tabnine tried to resolve local hostname and failed at that. May be 3.3.68 fixed that.

**Comment by amircodota** [comment]
@geovex I doubt there's anything in 3.3.68 that fixed it.

We try to resolve localhost when we connect to TabNine-deep-local which is the process running our local model.
Maybe you disabled the local model or something like that?

**Comment by faithanalog** [comment]
I had this issue, also on arch. Problem was actually that i didnt have an entry for localhost in my `/etc/hosts` file. Added `127.0.0.1    localhost` to `/etc/hosts` and everything worked fine from there.
