### ISSUE TITLE
What's the difference between local-model on and off? I cannot install the local model but still get completion.

### ISSUE THREAD

**Issue by RiverTwilight** [codota/TabNine#345]
**please complete the following information:**	
 - OS version: Win 10	
 - Editor: vscode
 - Editor version: 1.52.1
 - Programming language: js, ts
 - TabNine extension version: 3.2.8
 - Engine version (could be located within Tabnine Hub): 3.3.68-40

**Issue Details:**
I cannot install the local model. The model statu keeps "initializeing..." in Hub like this:
![image](https://user-images.githubusercontent.com/52880665/109245339-3abf5580-781b-11eb-9bd4-b028e9799eb3.png)

But I can still get completion when I'm coding.
![image](https://user-images.githubusercontent.com/52880665/109245589-c1743280-781b-11eb-8b13-037830502436.png)

So what's the difference between local-model on and off? Does it matter? Thanks.

**Comment by RiverTwilight** [comment]
By the way, when I visit `https://api.tabnine.com/model_metadata/v1` via Chrome I got a 404 error.

**Comment by RiverTwilight** [comment]
By the way, when I visit `https://api.tabnine.com/model_metadata/v1` via Chrome I got a 404 error.

**Comment by talcodota** [comment]
Hey,
It means you don't get our local deep learning code completions suggestions.
If you are not a pro user and don't have our deep completions cloud turned on, It means that your suggestions are probably shorter and their quality is lower.

Please try to click 'tabnine' on vscode status bar, then scroll to 'DEEP COMPLETIONS LOCAL' -> and turn on 'Enable Deep Completions Local'.
If it's already turned on, you might have some connection issues.
Please check it out and inform us.
About the 404 - it's not relevant because it's not a GET endpoint.
