### ISSUE TITLE
Running tabnine in local server mode

### ISSUE THREAD

**Issue by bigntallmike** [codota/TabNine#358]
I'm loving tabnine on my PC (Fedora Linux, VS Code, Python/C/C++/PHP/Rust) but I can't use the deep learning features on my laptop because it lacks the requirements to support it.
Given that these features are available on my PC, it would be great if tabnine supported a client/server model that allowed my machines to share one "active" learning copy of tabnine on the more powerful system and the rest simply talked with it for their suggestions, like using the cloud, but local.
Totally just a suggestion / thought.

**Comment by Eransho** [comment]
If your laptop doesn't meet the hardware requirements, you can sign up and create a Tabnine user to get access to our cloud deep learning.

**Comment by young1024** [comment]
![image](https://user-images.githubusercontent.com/25336944/129437434-6593d958-33e8-46de-b37f-e41e0b421d37.png)

**Comment by nomocas** [comment]
Hello All,

How could I access the "cloud deep learning" stuff? (I'm a paid user).

Because, when using tabnine (and other greedy extensions I confess) on my laptop (macbook pro, vs-code), it is draining all my battery so quickly that my laptop is not portable anymore... not a joke... it's annoying. (ok my laptop is from 2018 and has a declining battery, as a lot of people, but... still.)

So, yes, It would be awesome to be able to install/access a tabnine server somewhere to have all the deep learning computation decentralized.

Whatever, thanks for this great tool... ;)

++
