### ISSUE TITLE
tabnine was not working on vs code jupyter note book but working fine in vs code insider jupyter note book.please reslove it

### ISSUE THREAD

**Issue by mageshyt** [codota/TabNine#401]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

gz#1609

**Comment by jacksonkasi0** [comment]
Maybe this link solve your problem!

https://www.codegrepper.com/code-examples/shell/how+to+install+tabnine+in+jupyter+notebook
https://community.dataiku.com/t5/Using-Dataiku-DSS/How-to-enable-auto-completion-in-Jupyter-Notebook/m-p/2436

**Comment by maya-tabnine** [comment]
Since the legacy Jupiter extension uses a "custom editor," it will not be able to use TabNine completions as you normally do in .py files. However, this issue will be addressed soon thanks to the Jupyter extension "native editor" (currently in roll out).
So, as you said, to work around this issue you can use Visual Studio Code Insiders where the Jupyter extension will use the native editor.
Another possible workaround is to enable the experiment for the native editor as described here - 
https://github.com/codota/tabnine-vscode/issues/61#issuecomment-809257077
