### ISSUE TITLE
License invalidates if offline for too long

### ISSUE THREAD

**Issue by alexrobbins** [codota/TabNine#412]
After a couple of days offline (working from a cabin without wifi) my pro license stopped working.

I'm on a monthly plan and I still had two weeks left on the license, so I shouldn't have been invalidated.

Maybe encode an expiration date into a tabnine-signed license file, stored locally to allow offline usage? There are possible system time issues to work out, but I don't think most devs will mess with their system time to avoid $15 a month.

Thanks!

gz#2574

**Comment by maya-tabnine** [comment]
About the offline usage of Tabnine Pro, this can be problematic and may not work.
But I will pass on your suggestion to add support in such environments.

**Comment by D0ntPanic** [comment]
I just lost access on a yearly plan because my internet went out for 45 minutes. This seems a bit aggressive. Is this product going to be even usable when traveling by plane? I'm not going to pay the expensive airline fees just to activate something that should be running locally and has a year-long subscription active.

**Comment by D0ntPanic** [comment]
It seems to handle offline usage a lot better if you sign in with an account instead of using just the API key. After I uninstalled / reinstalled then signed in with the account instead of just using the API key, it survives internet outages (at least short ones) without falling back to free tier like before.

**Comment by zxvix** [comment]
I write code on our corporate server, which is behind a firewall and as a result does not have internet access. I would appreciate very much if TabNine pro could work under such environments. 
Because I use the vscode remote extension, the code is on the server but I edit remotely on my laptop, one potential solution could be validating licenses locally (on my laptop which has internet access) instead of directly on the server.
