### ISSUE TITLE
do not autocomplete certain file types?

### ISSUE THREAD

**Issue by thenanyu** [codota/TabNine#44]
There's a blacklist feature in autocomplete-plus for example. I'd like to turn suggestions off for text files like .txt, .md, etc

I have .tabnineignore set up but it seems like though it's not indexing those files it's still providing suggestions

**Comment by ishirav** [comment]
+1
I find that for some file types, I prefer the default auto-completion provided by SublimeText but there's no way to disable TabNine on these files.

**Comment by CurtisHumphrey** [comment]
+1 for example my css autocompleting is disabled with tabnine

**Comment by apollokit** [comment]
+1 I'd rather use another autocomplete option for .txt files

**Comment by apollokit** [comment]
Here's my current workaround for this. 

I guess I installed TabNine from source, don't really remember, but either way I have a TabNine.py file that I can edit in the packages folder (~/.config/sublime-text-3/Packages/TabNine/TabNine.py on my linux box). 

At the top of TabNine.py, I added a new command that can be invoked from the command palette:
`class TabNineDisableCommand(sublime_plugin.TextCommand):
    """ Hack to allow disabling of TabNine event handling, from a command
    """
    def run(self, edit):
        global GLOBAL_IGNORE_EVENTS
        GLOBAL_IGNORE_EVENTS = not GLOBAL_IGNORE_EVENTS

        if GLOBAL_IGNORE_EVENTS:
            print('TabNine disabled')
        else:
            print('TabNine enabled')
`
And I added another file in the same dir (TabNine dir) named tabnine.sublime-commands with:
`
[
  {
    "caption": "TabNine autocomplete HACK: toggle",
    "command": "tab_nine_disable"
  }
]
`
This adds "TabNine autocomplete HACK: toggle" as a command in the command palette. You can use this to deactivate tabnine as needed, from the command. 

I haven't extensively tested it, but seems to work and allow me to use regular tab complete in other places (in concert with https://github.com/Zinggi/DictionaryAutoComplete). No guarantee this will always work, since it hijacks the internal "GLOBAL_IGNORE_EVENTS" in TabNine.py.
