### ISSUE TITLE
Suggestion of gibberish text while typing

### ISSUE THREAD

**Issue by meghrathod** [codota/TabNine#440]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	Windows 10
 - Editor: [e.g. vscode, intelij, sublime]	vscode
 - Editor version:	1.59.0
 - Programming language: [e.g. js, ts, c++]	markdown/python(jupyter)
 - TabNine extension version: 3.4.22
 - Engine version (could be located within Tabnine Hub): 3.5.48-41

**Issue Details:**
A lot of time Tabnine suggest some random gibberish output which seems to have been trained on some random cryptographics or uuid based data and has no meaning whatsoever

![image](https://user-images.githubusercontent.com/23073422/129756698-b3533db4-2fb8-46a3-8f7f-93723df206d3.png)
Here is a screenshot of what I mean!

gz#5265

**Comment by talmago** [comment]
<img width="924" alt="Screen Shot 2021-08-18 at 13 35 13" src="https://user-images.githubusercontent.com/12200319/129887195-f0d67b9a-669a-433e-a31f-6dc5516df557.png">

**Comment by meghrathod** [comment]
Are u trying it on a Jupyter Notebook with Markdown? Because I've seen such inputs multiple times!

**Comment by talmago** [comment]
@meghrathod

**Comment by talmago** [comment]
@meghrathod This must be a result of some context found in your notebook. I'd also recommend you use the [jupyter notebook](https://www.tabnine.com/install/jupyter) extension since completions for the [VS Code notebooks are not officially supported](https://github.com/codota/TabNine/issues/401). 

gibberish? This must be a result of some context found in your notebook. 

trained on some random uuid based data? no, we don't do that.
