### ISSUE TITLE
Tabnine has no IP Whitelist

### ISSUE THREAD

**Issue by twocs** [codota/TabNine#442]
Please publish a whitelist of IP addresses for TabNine. ESET AV software cannot trust your frequent updates, but if you get some static IP addresses and publish the whitelist, then we can trust it's TabNine. I need a whitelist of IPs so Tabnine network activities can be trusted.

Support wasn't able to help me except to suggest that I don't subscribe to auto-updates!?!?

Seems like several times every week, Tabnine changes its IP address. Every time there's a new update, there's a new IP address. The latest update is trying to use update.tabnine.com on 18.67.113.51 but it changes many times a day. Not clear why TabNine is shifting around so much. It's using its own DNS? It's hard to trust a shifty company. I'm not going to blindly whitelist all of AWS just because Tabnine might be using ephemeral IPs. Most companies report the IP addresses they use, and I think Tabnine should, too. Add a link to the Tabnine home page that lists all the IP addresses.

Tabnine even gives examples of how to whitelist IP addresses. https://www.tabnine.com/code/javascript/functions/WHITELIST

gz#5375

**Comment by Tabnineteam** [comment]
Hello twocs,

Thanks for being a Tabnine user and for this detailed request. To make sure our updates get delivered to users as fast as possible we use a CDN, Amazon CloudFront, for distribution. By nature of CDNs, IP addresses occasionally change, and it makes sense that update.tabnine.com will get resolved to a different IP address due to changing traffic and network conditions. I hope this answers your question as for why the ip address is shifting around so much. As said I do think whitelisting is a bit tricky with CDNs but I did find this list of IP addresses used by Amazon CloudFront here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/LocationsOfEdgeServers.html

Please let me know if this helps with solving your issue and if there's anything else I can do to help you have the best experience with the product

Thanks again,

Nimrod Astarhan
Core Engineer
Tabnine
<br><p><em><small>°°°</small></em></p>
