### ISSUE TITLE
High memory  usage of 'TabNine-deep-local'

### ISSUE THREAD

**Issue by rehack** [codota/TabNine#450]
MacOS10.13
vscode Version: 1.59.1
Tabnine ext version | 3.4.26

Vscode is not in writing state, but ‘TabNine-deep-local’ memory usage is very high

![image](https://user-images.githubusercontent.com/9047357/131947089-2988a2b4-84ad-4c12-bc9c-ee0c7deeb075.png)

gz#6012

**Comment by yonip23** [comment]
Hi @rehack 
Tabnine takes up a significant amount of memory because it loads the gpt2 model to the ram, independent of what happens in vscode.
Fortunately, you can use our cloud option and disable the local service in the hub.
Also, pro users can choose their model size, which also helps reduce the memory footprint of Tabnine.

Hope this helps:)

**Comment by rehack** [comment]
Thank you all so much @yonip23 
 I switched to cloud mode, `TabNine-deep-local` process no longer occupied memory

**Comment by yonip23** [comment]
Just notice that if you're not working with neither local or cloud enabled, you're working with the very bear minimum Tabnine has to offer. Your choice 🙂

**Comment by MrMoshkovitz** [comment]
I have the same issue

**Comment by chirag127** [comment]
> Just notice that if you're not working with neither local or cloud enabled, you're working with the very bear minimum Tabnine has to offer. Your choice 🙂

Is there a option to disable the local deep learning?
