### ISSUE TITLE
GitHub co-pilots not working when using tabnine.

### ISSUE THREAD

**Issue by chirag127** [codota/TabNine#481]
**please complete the following information:**	
 - OS version: win 11
 - Editor: vs code
 - Programming language: .md	
 - Plugin Version: 3.5.1
 - Engine Version: 4.0.9-45

**Issue Details:**

Edit: there is some bug in tabnine or git-copilot that when the tabnine gives suggestions the GitHub-copilot is not able to show the recommendations.

Please don't give suggestions when the github co-pilot have given it . As most of the time the suggestion provided by the github co-pilot are better and more useful . You should give a option to turn on this feature if you do not want this option to be turned on by default. 

gz#8958

**Comment by maya-tabnine** [comment]
Hi, 
Since Tabnine is not related to co-pilot or any other extension, we have no way to disable it according to other extensions.
If you want, you can always disable Tabnine completions, although I think you'll miss out on a lot of great suggestions!
We would love to help with any other issue you may have :) Feel free to contact us at support@tabnine.com

**Comment by chirag127** [comment]
so, anything is possible or not? Actually the thing is that I want to use both cause github copilot gives bigger code snippets for free but tabnine is faster and give more relevant short snippets. 

if anything is not possible for this then can i close this issue?

**Comment by Gabrielcidral1** [comment]
I am also curious about this implementation. It would be great to use both
