### ISSUE TITLE
Hybrid mode causes unrecoverable system crash

### ISSUE THREAD

**Issue by JTrentSmart** [codota/TabNine#566]
**please complete the following information:**	
 - OS version: Ubuntu 20.04	
 - Editor: PyCharm	
 - Editor version: 2022.2.3, Build #PY-222.4345.23
 - Programming language: Python 3	
 - TabNine extension version: 0.7.26
 - Engine version: 4.4.158-60

**Issue Details:**

Recently installed TabNine, every attempt to use it in Hybrid mode leads to unrecoverable system crashes - No signal to monitor, all buttons/keys unresponsive including system power button. Power has to be manually cut at the PSU to shut down and restart.

Functionality appears normal in Cloud mode.

gz#18851

**Comment by amircodota** [comment]
Hi @JTrentSmart 

When you work in hybrid mode, we run the AI model locally.

That means TabNine will require a significant amount of cpu and RAM to operate.
On some systems, this may cause halts. It might be because there is a hardware issue that manifests when the system is busy, or because the system overheats.

If you can, please switch to hybrid mode, and monitor the running processes.
You would probably see a process named `TabNine-deep-local` consuming a lot of cpu.
You can also try to use the `sensors` utility to monitor cpu temperature.

Assuming that's the case, you can try to limit the amount of cpu that `TabNine-deep-local` process consumes.
You can use the `cpulimit` utility to limit cpu usage of TabNine-deep-local.

```
cpulimit --exe=TabNine-deep-local -l 200
```

I would really appreciate if you can report back to us - and let us know if it helped.
