### ISSUE TITLE
Could who can develop eclipse plugin to support it?

### ISSUE THREAD

**Issue by daringyun** [codota/TabNine#82]
Could who can develop eclipse plugin to support it?

**Comment by Nikronic** [comment]
I thought no longer eclipse in being used for years! :-)

**Comment by avichay77** [comment]
Eclipse is definitely on our plans . 
The community demand here helps to push it up. 
Will update here when we release a support for Eclipse

**Comment by 0ks4** [comment]
Username GitPopcorn has do great work by coding tabnine-eclipse-plugin. 
Link his repository https://github.com/GitPopcorn/tabnine-eclipse
Plugin is coded using java and i have read it every line. Doing that because install any software not recommendable if you aren't sure what code do. In my Java understanding, the GitPopcorn tabnine-eclipse extension is safe to use to get tabnine core and get auto suggest provided by tabnine working in eclipse!


I try use codota-eclipse plugin but that not working together whit Eclipse Code recommenders-plugin. Code recommenders plugin archived last year but it can still be installed and use.
I use Eclipse IDE 2020‑06 Eclipse IDE for Enterprise Java Developers -build
